# -*- coding: utf-8 -*-
"""Where each chart belongs: chart id -> (page, section, order).

Generated once from the Jekyll pages it replaces, so the Vue routes open with
exactly the charts, grouping and order the live site had. After that this file
is hand-maintained and is the single place that decides page composition -- a
chart missing from here is still built, but lands with page=None and is
reported by create_charts, which is how a chart shown nowhere gets noticed.

Section keys are page-scoped, so "energy_use" repeating across sectors is fine;
the locale key is pages.<page>.sections.<section>.
"""

CHART_PAGES = {
    "co2_emissions_sectors": ("overview", "overview", 0),
    "emissions_projection_yearly": ("overview", "projection", 1),
    "emissions_fuels_monthly": ("overview", "projection", 2),
    "emissions_fuels_yearly": ("overview", "projection", 3),
    "co2_emissions_sectors_with_lulucf": ("overview", "lulucf_shares", 4),
    "co2_emissions_sectors_shares": ("overview", "lulucf_shares", 5),
    "gross_inland_consumption_absolute": ("energy", "consumption", 0),
    "gross_inland_consumption_share": ("energy", "consumption", 1),
    "total_final_energy_use": ("energy", "consumption", 2),
    "total_final_energy_use_share": ("energy", "consumption", 3),
    "elec_prod_monthly": ("energy", "electricity", 4),
    "elec_prod_monthly_share": ("energy", "electricity", 5),
    "elec_prod_monthly_share_cons": ("energy", "electricity", 6),
    "elec_energy_use": ("energy", "electricity", 7),
    "elec_energy_use_share": ("energy", "electricity", 8),
    "elec_energy_use_share_cons": ("energy", "electricity", 9),
    "dh_energy_use": ("energy", "district_heating", 10),
    "dh_energy_use_share": ("energy", "district_heating", 11),
    "consumption_natural_gas_monthly": ("fossil-fuels", "natural_gas", 0),
    "consumption_natural_gas_yearly": ("fossil-fuels", "natural_gas", 1),
    "gas_sectoral_consumption_monthly": ("fossil-fuels", "natural_gas", 2),
    "gas_sectoral_consumption_yearly": ("fossil-fuels", "natural_gas", 3),
    "consumption_gasoline_monthly": ("fossil-fuels", "oil", 4),
    "consumption_gasoline_yearly": ("fossil-fuels", "oil", 5),
    "consumption_diesel_monthly": ("fossil-fuels", "oil", 6),
    "consumption_diesel_yearly": ("fossil-fuels", "oil", 7),
    "consumption_heating_oil_monthly": ("fossil-fuels", "oil", 8),
    "consumption_heating_oil_yearly": ("fossil-fuels", "oil", 9),
    "consumption_refinery_gas_monthly": ("fossil-fuels", "oil", 10),
    "consumption_refinery_gas_yearly": ("fossil-fuels", "oil", 11),
    "consumption_hard_coal_electricity_monthly": ("fossil-fuels", "coal", 12),
    "consumption_hard_coal_electricity_yearly": ("fossil-fuels", "coal", 13),
    "consumption_hard_coal_industry_monthly": ("fossil-fuels", "coal", 14),
    "consumption_hard_coal_industry_yearly": ("fossil-fuels", "coal", 15),
    "consumption_hard_coal_coke_ovens_monthly": ("fossil-fuels", "coal", 16),
    "consumption_hard_coal_coke_ovens_yearly": ("fossil-fuels", "coal", 17),
    "consumption_coke_oven_coke_monthly": ("fossil-fuels", "coal", 18),
    "consumption_coke_oven_coke_yearly": ("fossil-fuels", "coal", 19),
    "transport_emissions_sectors": ("transport", "overview", 0),
    "transport_final_energy_use": ("transport", "energy_use", 1),
    "transport_final_energy_use_share": ("transport", "energy_use", 2),
    "road_fuels_consumption": ("transport", "fuel_consumption", 3),
    "road_biofuels_consumption": ("transport", "fuel_consumption", 4),
    "kerosene_consumption": ("transport", "fuel_consumption", 5),
    "share_fuel_new_cars": ("transport", "vehicles", 6),
    "number_fuel_new_cars": ("transport", "vehicles", 7),
    "share_fuel_new_cars_yearly": ("transport", "vehicles", 8),
    "number_fuel_new_cars_yearly": ("transport", "vehicles", 9),
    "share_fuel_stock_cars": ("transport", "vehicles", 10),
    "number_fuel_stock_cars": ("transport", "vehicles", 11),
    "monthly_registrations_brands_shares": ("transport", "vehicles", 12),
    "monthly_registrations_brands_absolute": ("transport", "vehicles", 13),
    "yearly_registrations_brands_shares": ("transport", "vehicles", 14),
    "yearly_registrations_brands_absolute": ("transport", "vehicles", 15),
    "share_fuel_new_lorries_le3p5": ("transport", "vehicles", 16),
    "number_fuel_new_lorries_le3p5": ("transport", "vehicles", 17),
    "share_fuel_new_lorries_gt3p5": ("transport", "vehicles", 18),
    "number_fuel_new_lorries_gt3p5": ("transport", "vehicles", 19),
    "rail_tracks_abs": ("transport", "rail", 20),
    "rail_tracks_rel": ("transport", "rail", 21),
    "agriculture_emissions_sectors": ("agriculture", "overview", 0),
    "agriculture_final_energy_use": ("agriculture", "energy_use", 1),
    "agriculture_final_energy_use_share": ("agriculture", "energy_use", 2),
    "animal_livestock_population": ("agriculture", "animal_products", 3),
    "raw_cow_milk": ("agriculture", "animal_products", 4),
    "slaughtered_pig_meat": ("agriculture", "animal_products", 5),
    "slaughtered_cattle_meat": ("agriculture", "animal_products", 6),
    "slaughtered_chicken_meat": ("agriculture", "animal_products", 7),
    "fertilizer_nitrogen": ("agriculture", "animal_products", 8),
    "meat_consumption_total": ("agriculture", "animal_products", 9),
    "meat_consumption_per_capita": ("agriculture", "animal_products", 10),
    "milk_consumption_total": ("agriculture", "animal_products", 11),
    "milk_consumption_per_capita": ("agriculture", "animal_products", 12),
    "buildings_emissions_sectors": ("buildings", "overview", 0),
    "buildings_final_energy_use": ("buildings", "energy_use", 1),
    "buildings_final_energy_use_share": ("buildings", "energy_use", 2),
    "heating_oil_consumption": ("buildings", "energy_use", 3),
    "number_heating_systems": ("buildings", "heating_systems", 4),
    "share_heating_systems": ("buildings", "heating_systems", 5),
    "energy_industry_emissions_sectors": ("energy-industry", "overview", 0),
    "industry_final_energy_use": ("energy-industry", "energy_use", 1),
    "industry_final_energy_use_share": ("energy-industry", "energy_use", 2),
    "lulucf_emissions_sectors": ("lulucf", "overview", 0),
    "land_use_abs": ("lulucf", "land_use", 1),
    "land_use_rel": ("lulucf", "land_use", 2),
    "waste_emissions_sectors": ("waste", "overview", 0),
    "long_term_storage_c_disposal": ("waste", "overview", 1),
    "fluorinated_gases_emissions_sectors": ("f-gases", "overview", 0),
}


def lookup(chart_id):
    return CHART_PAGES.get(chart_id, (None, None, 0))
