# -*- coding: utf-8 -*-
"""National Inventory Report: land-use areas for the LULUCF page.

The NIR route into this project is a set of plain `year value` grids under
`data_raw/national_inventory_report/`. Only the six land-use area files are
read: the sub-sector emissions reader that used the rest was superseded by
`sources/eea.py` and is in `archive/national_inventory_sectors.py`, and those 28
files are still hand-transcribed leftovers from that era.

The six read here are not. They are generated by
`download/national_inventory.py` from the report PDF, which is where the table
numbers, the `pdftotext` invocation and the reasons for both are documented.

Forest land is reported in kHa and everything else in Ha, which is a property of
the report rather than a mistake here.

**The year axis is irregular and must stay irregular.** NIR 2026 publishes 1990,
1995, 2000, 2005 and then every year from 2010; the hand-transcribed files this
replaced held every year from 1990, and the axis used to be rebuilt with
`pd.date_range(first, last, freq="YS")` on that assumption. Against the current
files that generates 35 dates for 19 values -- the arrays would go out of step
and, being a different length, the failure lands somewhere downstream of here
rather than on the line that caused it. Series are aligned by date in
`series.align`, so the years are simply carried through as they are read.
"""

import os
from datetime import datetime

import numpy as np

from paths import DATA_RAW

NIR_DIR = DATA_RAW + "/national_inventory_report"

#: file stem -> display name, in palette order.
LAND_USES = {
    "forest_land": "Forests",
    "settlements": "Settlements",
    "crop_land": "Crop land",
    "grass_land": "Grass land",
    "wet_land": "Wet land",
    "other": "Other",
}

#: Forest land is the one file given in thousands of hectares.
_IN_KHA = ("forest_land",)


def land_uses():
    """Land-use areas in kHa, one series per use."""
    data_out = {"data": {}}
    for cat, label in LAND_USES.items():
        path = "%s/lulucf_%s.txt" % (NIR_DIR, cat)
        if not os.path.exists(path):
            raise FileNotFoundError(
                "%s is missing -- regenerate it with "
                "download/national_inventory.py." % path)
        with open(path, "r") as fp:
            lines = fp.readlines()

        years = []
        areas = []
        for line in lines:
            splits = line.split()
            if not splits:
                continue
            years.append(int(splits[0]))
            # kHa throughout: the Ha files are divided down, the kHa one is not.
            areas.append(float(splits[1]) / (1 if cat in _IN_KHA else 1000))

        data_out["data"][label] = {
            "x": [datetime(year=y, month=1, day=1) for y in years],
            "y": np.array(areas),
        }
    return data_out
