
title: Austria Transition Tracker
author: BethaData
description: >- # this means to ignore newlines until "baseurl:"
baseurl: / # the subpath of your site, e.g. /blog
url: https://bethadata.github.io # the base hostname & protocol for your site, e.g. http://example.com
repo_name: https://github.com/bethadata/austria-transition-tracker

# Build settings
theme: minima
classes: wide 
plugins:
  - jekyll-feed

sector_pages:
  - agriculture.md
  - buildings.md 
  - energy_industry.md
  - lulucf.md 
  - fluorinated_gases.md
  - transport.md
  - waste.md
